openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger
  license:
    name: MIT
servers:
  - url: http://localhost:8081/
paths:
  /api/v1/message:
    get:
      summary: get messages by filter
      operationId: getMessage
      tags:
        - message
      parameters:
        - name: page
          in: query
          required: false
          schema:
            type: integer
            default: 0
        - name: size
          in: query
          required: false
          schema:
            type: integer
            default: 20
        - name: sort
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: returns page of messages
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessagePageDto"
    post:
      summary: create message
      operationId: createMessage
      tags:
        - message
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MessageCreateRequest"
      responses:
        '201':
          description: message created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessageDto"
    put:
      summary: update message
      operationId: updateMessage
      tags:
        - message
      parameters:
        - name: messageId
          in: path
          required: true
          description: The id of the message to update
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MessageUpdateRequest"
      responses:
        '200':
          description: returns updated message
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessageDto"
    delete:
      summary: delete message by id
      operationId: deleteMessageById
      tags:
        - message
      parameters:
        - name: messageId
          in: path
          required: true
          description: The id of the message to delete
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: message deleted

components:
  schemas:
    MessageCreateRequest:
      type: object
      required:
        - source
        - payload
        - dist
      properties:
        payload:
          type: string
        source:
          type: string
        dist:
          type: string
    MessageUpdateRequest:
      type: object
      required:
        - source
        - payload
        - dist
      properties:
        payload:
          type: string
        source:
          type: string
        dist:
          type: string
    MessageDto:
      type: object
      required:
        - id
        - createdAt
        - updatedAt
        - payload
        - source
        - dist
      properties:
        id:
          type: integer
          format: int64
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        payload:
          type: string
        source:
          type: string
        dist:
          type: string
    MessagePageDto:
      type: object
      required:
        - size
        - number
        - totalElements
        - totalPages
        - content
      properties:
        size:
          type: integer
        number:
          type: integer
        totalElements:
          type: integer
          format: int64
        totalPages:
          type: integer
        content:
          type: array
          items:
            $ref: "#/components/schemas/MessageDto"