version: '3'
services:
  postgres:
    image: postgres
    ports:
      - '65438:5432'
    environment:
      POSTGRES_DB: bloat
      POSTGRES_USER: bloat
      POSTGRES_PASSWORD: bloat
      POSTGRES_INITDB_ARGS: "-E=UTF8 --lc-collate=C --lc-ctype=C"

